In [7]:
import pandas as pd
import numpy as np

In [8]:
M = np.array([[3,-2,0],[-2,1,-3],[4,6,1]])
b = np.array([8,-20,7])
np.linalg.solve(M,b)

array([ 2., -1.,  5.])

In [9]:
M

array([[ 3, -2,  0],
       [-2,  1, -3],
       [ 4,  6,  1]])

In [10]:
b

array([  8, -20,   7])